# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PartialHistogram
                                 A QGIS plugin
 This plugin creates histogram of a part of a raster.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-20
        copyright            : (C) 2021 by Murat ÇALIŞKAN
        email                : caliskan.murat.20@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PartialHistogram class from file PartialHistogram.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .partial_histogram import PartialHistogram
    return PartialHistogram(iface)
